ビュー作成
yoshimasa1125/chat-space pull request #2
Opened 2019-03-19 07:19 UTC by yoshimasa1125

すみません、ブランチを新しく作り忘れましたので、ブランチ名が”データベース設計のままです”
https://i.gyazo.com/58e9f9fe3d489a2d5f0fbac05f3d7ca7.png

2019-03-19 07:25 UTC, ReoKuriyama requested changes
インデント多数ずれている場所があるので見直してください

2019-03-19 07:25 UTC, ReoKuriyama commented on app/assets/stylesheets/_leftside.scss
> +  	width: 300px;
インデントずれていますね

2019-03-19 07:25 UTC, ReoKuriyama commented on app/assets/stylesheets/_leftside.scss
> +.wrapper{
ファイル名の中の記述が一致していないように感じます。
サイドバーと分けるのであれば、ファイルも分けましょう

2019-03-19 08:03 UTC, yoshimasa1125 commented on app/assets/stylesheets/_leftside.scss
> +.wrapper{
ファイルを分けました

2019-03-19 08:03 UTC, yoshimasa1125 commented on app/assets/stylesheets/_leftside.scss
> +  	width: 300px;
インデント、修正いたしました

2019-03-19 08:07 UTC, ReoKuriyama commented
htmlの方も分けましょう
renderメソッドを使えば実現できます

2019-03-19 09:51 UTC, TOMARUMARU reviewed
class名をBEMで命名し、&記法を使って記述しましょう

2019-03-20 09:21 UTC, yuki-uchida commented on app/assets/stylesheets/_main.scss
> +        .rightbox__btn{
この辺りもアンバサンド出かけます

2019-03-20 09:21 UTC, yuki-uchida commented on app/assets/stylesheets/_main.scss
> +      .message-box{
この辺りも見直しましょう

2019-03-20 10:08 UTC, TOMARUMARU commented on app/assets/stylesheets/_wrapper.scss
> +}
最下行は改行いれましょう

2019-03-20 10:08 UTC, TOMARUMARU commented on app/assets/stylesheets/messages.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
使用しないファイルは消しましょう

2019-03-20 10:08 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう

2019-03-20 10:08 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +!!!
mailerファイル使用しないので消しましょう

2019-03-20 10:08 UTC, TOMARUMARU commented on app/views/layouts/mailer.text.haml
> += yield
mailerファイル使用しないので消しましょう

2019-03-20 10:08 UTC, TOMARUMARU commented on config/routes.rb
> +	get '/messages' => 'messages#index'
rootにあるので不要です

2019-03-20 10:21 UTC, TOMARUMARU reviewed
ハッシュロケットが修正されていません！

2019-03-20 10:44 UTC, TOMARUMARU approved these changes
LGTM

2019-03-20 10:47 UTC, merged